#pragma once

#include "stdafx.h"
#include "MassStorageDevice.h"

#define HEIMDALL_DEVICE 0x8008
#define IOCTL_HEIMDALL_ADD_DEVICE				CTL_CODE(HEIMDALL_DEVICE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HEIMDALL_REMOVE_DEVICE			CTL_CODE(HEIMDALL_DEVICE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HEIMDALL_START_PLUG_NOTIFICTAION	CTL_CODE(HEIMDALL_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_HEIMDALL_STOP_PLUG_NOTIFICTAION	CTL_CODE(HEIMDALL_DEVICE, 0x803, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_HEIMDALL_QUERY_DEVICE				CTL_CODE(HEIMDALL_DEVICE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _IOCTL_PACKET
{
	WCHAR DeviceId[DeviceIdMaximumLength];
	WCHAR InstanceId[InstanceIdMaximumLength];
} IOCTL_PACKET, * PIOCTL_PACKET;

NTSTATUS ControlInit(PDRIVER_OBJECT DriverObject);